### ISSUE TITLE
Not showing databases in sdcard

### ISSUE THREAD

**Issue by Aexyn** [infinum/android_dbinspector#19]
My app makes database in Phone Storage and SD card. It is Showing data of Phone Storage but not of sdcard. Location of my db id sdcard/android/data/<myapp_package_name>/files/<database.db>. Is it not supported or just an issue??

**Comment by reisub** [comment]
Hi @Aexyn,
we never really needed this but I agree it's a valid use case.

I think this is possible provided we have a way of finding the databases on the sdcard. Currently, we find databases by looking in the directory which android uses to store sqlite databases. I don't think we have something like this on the sdcard. (Can anyone confirm / deny? @zplesac)

I see 2 options:
1) Recursively check all the files in the sdcard to see if any of them are sqlite databases. I'm not sure if we have a way of doing this. Maybe we can use the `file` command (http://linux.die.net/man/1/file)?

2) Pass in (through intent extra) a list of database locations which are not in the standard database folder of the app so we can show those, too. This complicates usage when you have sdcard databases because you can't just use the launcher icon but have to start DbInspectorActivity explicitly.

I'm not sure when we will have time to investigate these options further, maybe in a couple of weeks time.
Would you care to investigate this and make a pull request?

**Comment by reisub** [comment]
I just got a better idea.
We can define an empty string array in resources of dbinspector so the app can override this string rray like this:
```xml
<string-array name="dbinspector_external_databases">
  <item>/sdcard/android/data//files/my-db.sqlite</item>
</string-array>
```

And we just use it to add those databases to the list.
How does that sound, @Aexyn ?

**Comment by Aexyn** [comment]
How about searching in this folder only

Environment.getExternalStorageDirectory()+"/Android/"+getApplicationContext().getPackageName();

**Comment by Aexyn** [comment]
Or Search in this
String pathOfOurApp = getApplicationContext().getExternalFilesDir(null).getAbsolutePath();

this is the path given to app to store its personal data on external sdcard. Sd card may be present , may be not

**Comment by reisub** [comment]
Sure, this can work if we can determine if the file is an sqlite database without relying on the extension. (See https://github.com/infinum/android_dbinspector/issues/14)
We'll see what we can do about this when we find some time. In the meantime, feel free to experiment or implement it yourself.

**Comment by Aexyn** [comment]
I Have created a pull request. See if that works

**Comment by reisub** [comment]
I merged in your pull request.
