### ISSUE TITLE
Showing databases only when app is killed.

### ISSUE THREAD

**Issue by Aexyn** [infinum/android_dbinspector#20]
The app is showing only Phone storage databases (see #19) but that too when I follow the same steps in sequence:
* I start my app
* Wait for it till it get data from server and create database
* kill app
* Open the dbInspectorActivity

If I open the dbInspectorActivity while my main app is running.. It will reopen the  app, not database list. May be it a bug, may be it needs documentation

**Comment by reisub** [comment]
Hi @Aexyn,
this was solved with the following PR:
https://github.com/infinum/android_dbinspector/pull/18

.. and will be released with the next release of DbInspector which is expected in the following weeks.
Of course, you can always build your own aar from master and include it locally instead of via maven.
