### ISSUE TITLE
Impractical with a lot of text in database

### ISSUE THREAD

**Issue by reisub** [infinum/android_dbinspector#31]
We should add an option to have a preference to toggle showing all content or ellipsize it (default).

**Comment by zplesac** [comment]
+1 for this

**Comment by brcinho** [comment]
+1 for this 
Also one argument from other side is that for some data types like numeric with decimal points, the digits in normal view get cut off after fourth digit, which caused a lot of debugging for me until I found that I was actually storing the latitude and longitude with correct amount of decimals and that DB Inspector was cutting digits off when showing data from table.

**Comment by reisub** [comment]
We could also show ellipsized contents on the table contents screen and have another row details screen which would contain the full content of a single row.
So far we haven't found the time to implement this and I don't think we'll find it in the near future so if anyone wants to work on this, feel free!

**Comment by bojankoma** [comment]
Since this a very different direction of how we should handle a lot of data in a single cell, we can continue discussion in a recently open [issue](https://github.com/infinum/android_dbinspector/issues/62). This new issue suggests only UI manipulations and not changing actual data, which is more inline with what this project should do.
