### ISSUE TITLE
Ability to write custom queries

### ISSUE THREAD

**Issue by brcinho** [infinum/android_dbinspector#40]
It would be great to have the ability to perform custom queries on a data base, whether to find out a specific query plan execution or to perform joins.

Potentially it can skyrocket the usability of this great product.

I can apply for trying to solve this task. Prior to that, I would need your opinion and confirmation if it can be done.

**Comment by reisub** [comment]
Hi @brcinho, that sounds great!
@zplesac already started some work on that a while ago, but he was since swamped in other work so he didn't have time to continue.
Maybe you can reuse some of the code?

I would be happy to comment your code and help with ideas. I'm pretty sure it can be done.
Let me know when you have something to show :)
